sudo: required
services:
- docker
language: go
go:
- 1.7
before_install:
- echo -e "machine github.com\n  login $GITHUB_USER\n  password $GITHUB_PASS" >> ~/.netrc
script:
- make
after_success:
- make coveralls
env:
  global:
  - secure: udHxDWDOP6688+nxPyblKMPptstQkC7TYjEfODOQArUPov5uuRmNtJTG1eDhMfGTCKwSrPigug3HxrvZtiVrPl/nwfKAp/Sa7jKnuxOB+3IFUnxQyCxjtLs6iaNRHblwD9yY7Dyr7URAep19nYJ8sinZ/nEMm40wcWJwrsAT/4/w3Imxv3VNzhWOIwon/jl4Hl9rZzugCUwAQwMRq5saZhap5/0Uhzb4jKL5tp9r2S2HeDcWm5GQwFCH/kAx917tIqdQXTSqrduWnraxYi0hbb9Z2sIKDYhNjMuMBYXFvLEyRoByvlwMuf/LZ7MbfzHvScw8DKqkLbz48iQmnlRNWpYaFlgYKYNy0P96DBVVpFY3GBc/NNCrrmTi/8M+HwG4Ae3euhL4eHMHwh7P6o0IZPidYog1KDpU7co9NoDc3pLU+l0ZBM8AKkfudOjtUG2PZn9pRApLJxTJv6BC4c/b7TZtNlzJ2/RSdsbd312tymWgvcpYguYvClVy2xz5fk9AXoCH6ho37sGuKnPsNd2cw+AzQnAk1H9iJAUo57lPtEu0AO2IHXYqK4hWABxqolZHNoOVnKKra6uEqoL5wRaEK1soxLzSm78MJaPea2C8hdN5McHSOd8zNzc4iljL/B9pgpEBgFeru8AQDFIXzrI0DMYhuuXTXwyjpbwh9cicdr0=
  - secure: kyCYGqopjejN0DYMFGNOmOq9uHuGV/ssi2dti/6KC3pWdwCuS7af2kiUqR5WWaN0yGhvr66cN7UcAZLMEg/71sMMiFBa0Dp8H5Hl8CL5/UeitAINfX3spRsq4xpo3u5bRweU7s2/8I1wTtq+hXRRVNO/rVB2mN6reVPsEzSZnexZxa60EHhdA1P4Gbg8MNmNJijEuR8NZpx40ngd74CK5CDGgaid7AtEtYhlC9jp7zOMGxZjCniTob7qvnXT5Bf/i+8N7wZDl/JqT6PkGVNiJTB+TCFQEePGXhYds3biehCmIGqrCpFAahm5MVay/R5Q8HNIU0jyuTjkBv1RJGhYZ+DSm4+C3+4Tfo04lANAA/ZTeI8Nnb29fJyXoeAYfmD2oyEsftcoDYt+2L/2/wtSvmtXCZhrSalLRwAhLhRNIEpDlQtJEbh2AYjVZU6NZQks+7vXWQy+2x6mf3haAG/aPd2NX0308orMx42RV6so5XeYNEzIt34glfWiKATVqB/l6wgyJ5kZi1zHwDstByDJaXFjnPxUr406EEPZR3R9ypqcjPaZbb+xui5xsBLZ0nxmyHPytVM/6nqNv3q/r0iipO7NmdWnJk7u9dtxEt+jDkxMm8ccbXxKdaxSJVv+7HEbRP5yHckvBzRmhtTMi5hJFDq6yEcflpgQwKjaMY/2dxo=
notifications:
  slack:
    secure: uFsPAXCnFrBfAYDTaNVDcRMmpV++qJ4VgnZhYhw/A5e8V7kGDIrsXd1fa9FCjOHmlaTIKkBQDFucp7oxdpBRhOpvuE/IFcXNCUkklojvQEtknFSDiNysxxF5QV98ltXBsK/1smVHBeJbfwQ3nmitXObVafz3cDITK3ZzBVCGdmH4RHV2kj92+j7cYPUPjF9u7yswXJS6iSF0JqWBEe1rCAKa4setfxRguPH/G39fjlpdJlHNwsuiOLDY9i2vg+LUKlioaESrppkwljNdZIVdDAswyiCHyhHog/i6vhmw8m2vbBUo1Dek45OVVnUdKqltg/Ded5GpZ2VDpJkGenUSsVLwV3krKQeT2OTWzHuBeuLZY9XJAbOjOgh6YQ5cEeHsFlfbaylqPkd3W6gHV/1CvhxzXmsqsDOwyfIAJqr8vSwKTd6y/tBf1gN6bdg00SSuzUDjpe5SfoYx2KEizIT/e+Ne4t9iPVRG16Mn1hDJC/arBOCBI9o2LYYaDY9cnvRTM6TYUU1WetXdqvUtNqnf4uZccBB109YGOhCv3wqQNnLe64geKlr+9T0+PWc5Q2xTjACLWmg3/8A4XgoWq3h7PA6MAjeNoJWLx3C/X43T+iBAJPL0DN2TMl8IYzs8Y+Wc9zuh5dEaZoBgmvnWw5+6yOkNnLBDzt4X/+j2/nTxndM=
